In [1]:
# -*- coding: utf-8 -*-
import dataiku
import pandas as pd, numpy as np
from dataiku import pandasutils as pdu

In [5]:
# Read recipe inputs
aspects_grouped = dataiku.Dataset("aspects_grouped")
df = aspects_grouped.get_dataframe()

In [15]:
def weighted_ave(x):
    d = {}
    d['weighted_ave_nltk'] = (x["mean_polarity_nltk"] * x["count"]).sum() / x["count"].sum()
    d['weighted_ave_tb'] = (x["mean_polarity_textblob"] * x["count"]).sum() / x["count"].sum()
    return pd.Series(d, index=['weighted_ave_nltk', 'weighted_ave_tb'])

In [17]:
df_grouped = df.groupby(["product_id", "group"]).apply(weighted_ave).reset_index()

         product_id      group  weighted_ave_nltk  weighted_ave_tb
0        Air France  dist_food          -0.011069         0.024983
1        Air France  dist_lugg           0.042001         0.044943
2        Air France  dist_punc           0.138251         0.214327
3        Air France  dist_staf          -0.012110        -0.008660
4   Delta Air Lines  dist_food          -0.013386         0.026777
5   Delta Air Lines  dist_lugg           0.035909         0.043176
6   Delta Air Lines  dist_punc           0.139220         0.212696
7   Delta Air Lines  dist_staf          -0.018500         0.014773
8          Emirates  dist_food          -0.008417         0.028635
9          Emirates  dist_lugg           0.049050         0.074388
10         Emirates  dist_punc           0.341109         0.513309
11         Emirates  dist_staf          -0.058547         0.033493
12        Lufthansa  dist_food           0.023688         0.049680
13        Lufthansa  dist_lugg           0.061289         0.059811
14        Lufthansa  dist_punc           0.042220         0.056931
15        Lufthansa  dist_staf           0.011356        -0.005159
16          Ryanair  dist_food          -0.033452         0.012121
17          Ryanair  dist_lugg          -0.022104        -0.061807
18          Ryanair  dist_punc           0.026688         0.032253
19          Ryanair  dist_staf          -0.006105        -0.091667
20  United Airlines  dist_food          -0.018503         0.023483
21  United Airlines  dist_lugg           0.036566         0.043262
22  United Airlines  dist_punc           0.137949         0.209355
23  United Airlines  dist_staf          -0.018500         0.014773

In [ ]:
# Compute recipe outputs from inputs
# TODO: Replace this part by your actual code that computes the output, as a Pandas dataframe
# NB: DSS also supports other kinds of APIs for reading and writing data. Please see doc.

sentiment_by_companies_df = df_grouped # For this sample code, simply copy input to output

In [0]:
# Write recipe outputs
sentiment_by_companies = dataiku.Dataset("sentiment_by_companies")
sentiment_by_companies.write_with_schema(sentiment_by_companies_df)